/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	xworldv1 "xworld.cn/pkg/apis/xworld/v1"
	versioned "xworld.cn/pkg/client/clientset/versioned"
	internalinterfaces "xworld.cn/pkg/client/informers/externalversions/internalinterfaces"
	v1 "xworld.cn/pkg/client/listers/xworld/v1"
)

// XServerInformer provides access to a shared informer and lister for
// XServers.
type XServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.XServerLister
}

type xServerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewXServerInformer constructs a new informer for XServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewXServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredXServerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredXServerInformer constructs a new informer for XServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredXServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XworldV1().XServers(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XworldV1().XServers(namespace).Watch(options)
			},
		},
		&xworldv1.XServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *xServerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredXServerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *xServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&xworldv1.XServer{}, f.defaultInformer)
}

func (f *xServerInformer) Lister() v1.XServerLister {
	return v1.NewXServerLister(f.Informer().GetIndexer())
}
