/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	xworldv1 "xworld.cn/pkg/apis/xworld/v1"
)

// FakeXServers implements XServerInterface
type FakeXServers struct {
	Fake *FakeXworldV1
	ns   string
}

var xserversResource = schema.GroupVersionResource{Group: "xworld.cn", Version: "v1", Resource: "xservers"}

var xserversKind = schema.GroupVersionKind{Group: "xworld.cn", Version: "v1", Kind: "XServer"}

// Get takes name of the xServer, and returns the corresponding xServer object, and an error if there is any.
func (c *FakeXServers) Get(name string, options v1.GetOptions) (result *xworldv1.XServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(xserversResource, c.ns, name), &xworldv1.XServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xworldv1.XServer), err
}

// List takes label and field selectors, and returns the list of XServers that match those selectors.
func (c *FakeXServers) List(opts v1.ListOptions) (result *xworldv1.XServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(xserversResource, xserversKind, c.ns, opts), &xworldv1.XServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &xworldv1.XServerList{ListMeta: obj.(*xworldv1.XServerList).ListMeta}
	for _, item := range obj.(*xworldv1.XServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested xServers.
func (c *FakeXServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(xserversResource, c.ns, opts))

}

// Create takes the representation of a xServer and creates it.  Returns the server's representation of the xServer, and an error, if there is any.
func (c *FakeXServers) Create(xServer *xworldv1.XServer) (result *xworldv1.XServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(xserversResource, c.ns, xServer), &xworldv1.XServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xworldv1.XServer), err
}

// Update takes the representation of a xServer and updates it. Returns the server's representation of the xServer, and an error, if there is any.
func (c *FakeXServers) Update(xServer *xworldv1.XServer) (result *xworldv1.XServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(xserversResource, c.ns, xServer), &xworldv1.XServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xworldv1.XServer), err
}

// Delete takes name of the xServer and deletes it. Returns an error if one occurs.
func (c *FakeXServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(xserversResource, c.ns, name), &xworldv1.XServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeXServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(xserversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &xworldv1.XServerList{})
	return err
}

// Patch applies the patch and returns the patched xServer.
func (c *FakeXServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *xworldv1.XServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(xserversResource, c.ns, name, pt, data, subresources...), &xworldv1.XServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xworldv1.XServer), err
}
